import { GeometryParameter } from "../../parameter/parameter";
export class Box {
  static cube(size: number, color: [number, number, number, number]) {
    let verticesData = [
      -size,
      -size,
      size,
      size,
      -size,
      size,
      size,
      size,
      size,
      -size,
      size,
      size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      size,
      size,
      -size,
      size,
      -size,
      -size,
      -size,
      size,
      -size,
      -size,
      size,
      size,
      size,
      size,
      size,
      size,
      size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      -size,
      size,
      -size,
      size,
      -size,
      -size,
      size,
      size,
      -size,
      -size,
      size,
      size,
      -size,
      size,
      size,
      size,
      size,
      -size,
      size,
      -size,
      -size,
      -size,
      -size,
      -size,
      size,
      -size,
      size,
      size,
      -size,
      size,
      -size,
    ];

    let v = 1.0 / Math.sqrt(3.0);

    let normalData = [
      -v,
      -v,
      v,
      v,
      -v,
      v,
      v,
      v,
      v,
      -v,
      v,
      v,
      -v,
      -v,
      -v,
      -v,
      v,
      -v,
      v,
      v,
      -v,
      v,
      -v,
      -v,
      -v,
      v,
      -v,
      -v,
      v,
      v,
      v,
      v,
      v,
      v,
      v,
      -v,
      -v,
      -v,
      -v,
      v,
      -v,
      -v,
      v,
      -v,
      v,
      -v,
      -v,
      v,
      v,
      -v,
      -v,
      v,
      v,
      -v,
      v,
      v,
      v,
      v,
      -v,
      v,
      -v,
      -v,
      -v,
      -v,
      -v,
      v,
      -v,
      v,
      v,
      -v,
      v,
      -v,
    ];

    let colorData = [];
    for (let i = 0; i < verticesData.length / 3; i++) {
      colorData.push(color[0], color[1], color[2], color[3]);
    }

    let textureCoord = [
      0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0,
      1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0,
      0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
      1.0, 0.0, 1.0,
    ];

    let indicesData = [
      0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7, 8, 9, 10, 8, 10, 11, 12, 13, 14, 12,
      14, 15, 16, 17, 18, 16, 18, 19, 20, 21, 22, 20, 22, 23,
    ];

    const boxData: GeometryParameter = {
      vertices: verticesData,
      normal: normalData,
      color: colorData,
      textureCoord: textureCoord,
      indices: indicesData,
    };

    return boxData;
  }
}
